# ENV VARS:
# - NPM_TOKEN
# + GITHUB_TOKEN (by default)

#name: Build, Release and Publish Package to npmjs
name: Build and Publish Package to npmjs
#on:
#  push:
#    tags:
#      - "*.*.*"
on:
  release:
    types: [ published ]
#    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #      - name: Get the version # get the version from the tag
      #        id: get_version
      #        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: actions/setup-node@v2 # Setup .npmrc file to publish to npm
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

#      - name: create Release
#        uses: softprops/action-gh-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          #          body_path: ${{ github.workspace }}/CHANGELOG.md
#          body_path: CHANGELOG.md
#          files: |
#            LICENSE.md
#            CONTRIBUTOR_LICENSE_AGREEMENT.md
